version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      
    command: sh -c "npm i && node src/database/syncDb.js && npm start"
  
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=DevBlog
      - MYSQL_ROOT_PASSWORD=123456

    ports:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      
volumes:
  db:
    driver: local